# Generated by Django 5.1.4 on 2024-12-16 19:06

import advertisement.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=19)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "ACTIVE"), (2, "RESOLVED"), (3, "SOLD")], default=1
                    ),
                ),
                (
                    "main_picture",
                    models.ImageField(upload_to=advertisement.models.main_pictures_path),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
